apiVersion: v1
kind: PersistentVolume
metadata:
  name: global-pv
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ~/Workspace/K8s/volumes/global
